
spring:
  application:
    name: hello-spring-cloud-web-admin-feign

server:
  port: 8766
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/




#开启hystrix
feign:
  hystrix:
    enabled: true

